[package]
name = "nyat"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.17"
nix = "0.26.2"
nom = "7.1.3"
pollster = "0.3.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
wgpu = "0.16.0"
wgpu_glyph = "0.20.0"
winit = "0.28.3"
